'use client'

import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Navigation from './components/navbar'
import Footer from './components/footer'
import Ticker from './components/ticker'
import { Provider } from 'react-redux'
import { store } from './store'
import Partners from './components/partners'
import { useRouter, usePathname } from 'next/navigation'
import { useEffect } from 'react'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700'] })
const metadata: Metadata = {
  title: 'Bandage',
  description: 'Generated by create next app',
}

const allowedRoutes = ['/auth', '/auth/signup'];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const router = useRouter();
  const pathname = usePathname();
  useEffect(() => {
    if (typeof localStorage !== "undefined") {
      const token = localStorage.getItem('token');
      if (!token && !allowedRoutes.includes(pathname)) {
        router.push('/auth');
      }
    }
  }, [router, pathname]);
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex">
          <Provider store={store}>
            <Ticker />
            <Navigation />
            <main >{children}</main>
            <Partners />
            <Footer />
          </Provider>
        </div>
      </body>
    </html>
  )
}
