'use client'

import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Navigation from './components/navbar'
import Footer from './components/footer'
import Ticker from './components/ticker'
import { Provider } from 'react-redux'
import { store } from './store'
import Partners from './components/partners'
import { useRouter, usePathname } from 'next/navigation'
import { useEffect, useState } from 'react'
import { useLocalStorage } from './useLocalStorage'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700'] })
const metadata: Metadata = {
  title: 'Bandage',
  description: 'Generated by create next app',
}

const allowedRoutes = ['/auth', '/auth/signup'];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const router = useRouter();
  const [token, setToken] = useLocalStorage('token', '');
  const pathname = usePathname();
  const [prevPathName, setPrevPathName] = useState(pathname);
  useEffect(() => {
    if (!token && !allowedRoutes.includes(pathname)) {
      setPrevPathName(pathname);
      router.push('/auth');
    } else if (!allowedRoutes.includes(prevPathName)) {
      router.push(prevPathName);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [token]);
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex">
          <Provider store={store}>
            <Ticker />
            <Navigation />
            <main >{children}</main>
            <Partners />
            <Footer />
          </Provider>
        </div>
      </body>
    </html>
  )
}
